# Generated by Django 5.0.3 on 2024-03-24 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("done", models.BooleanField()),
                ("edit_date", models.DateTimeField(verbose_name="edit date")),
                (
                    "parent_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lists.todolist"
                    ),
                ),
            ],
        ),
    ]
